name: CMake
on: [ push ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            cmake_extra: -DCMAKE_C_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-9
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create build environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE ${{matrix.cmake_extra}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Dist
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target install --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C Release

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: ${{github.workspace}}/dist/*
